version: '3.1'

services:

  alpine:
    container_name: alpine
    build: ./web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_HOSTS_DIR}:/etc/nginx/conf.d/
      - ${APP_DIR}:/app/sites

  mysql:
    container_name: mysql
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80

networks:
  default:
    driver: bridge

